### ISSUE TITLE
!!! tip "Note"

### ISSUE THREAD

**Issue by birgitpolkner** [citrix/xenserver-sdk#2]
The !!! tip "Note" appears just like that for translation. We are assuming that it needs to stay as is in English.

It looks odd here in GitHub... presumably it will be OK after you compile? Do you want me to provide a translation for "Note"?

**Comment by ajitchelat** [comment]
You can translate "Note" !!! tip "Note" is the syntax we use as prescribed by the markdown admonition extension used in the compiler. The word in double quotes will appear as the title of the admonition.

**Comment by birgitpolkner** [comment]
OK, great. I will let the translators know.
