### ISSUE TITLE
Split sentences

### ISSUE THREAD

**Issue by birgitpolkner** [citrix/xenserver-sdk#3]
Just FYI: Sentences like this one are difficult for translation:

For example, using the Linux command line tool cURL:
curl http://root:foo@myxenserver1/export?uuid=<vm_uuid> -o <exportfile>
will export the specified VM to the file exportfile.

Sentence structure is different from language to language, so this split often causes problem. The translator did not complain for this particular file, so it is fine here. However, we generally recommend to start a new sentence after an example or a list item.

**Comment by ajitchelat** [comment]
Fixed the specific issue mentioned in the comment. I will read through the entire file and all other documents and fix issues with split sentences wherever they occur.
